version: "3.6"

services:

  artificial-intelligence:
    # Building the image
    <<: &artificial-intelligence
      image: "artifical-intelligence:latest"
      build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "10003:10003"
    env_file: 
      - env_file