version: "3.6"

services:

  ai_ms_worker:
    # Building the image
    <<: &ai_ms_worker
      image: "ai_ms_worker:latest"
      build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "10003:10003"
    env_file: 
      - env_file